[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=0
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=A
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=Are You Sure You Want To Install Antivirus?
DisplayLicense=C:\Users\sttev\Downloads\Licence Agrement.txt
FinishMessage=Finished
TargetName=C:\Users\sttev\Desktop\Antivirus\Antivirus.exe
FriendlyName=Install Antivirus
AppLaunched=Antivirus.exe
PostInstallCmd=Antivirus.exe
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="Antivirus.exe"
FILE1="md5.txt"
FILE2="READ ME!.txt"
[SourceFiles]
SourceFiles0=C:\Users\sttev\Desktop\Antivirus\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
